os: linux
dist: trusty
sudo: required
language: cpp
compiler: gcc

before_install:
  - sudo apt-get update
  - sudo apt-get upgrade -y

install: 
  - sudo apt-get install -y axel xz-utilsgit-core gnupg flex bison gperf libsdl-dev libesd0-dev libwxgtk2.6-dev build-essential zip curl libncurses5-dev zlib1g-dev ia32-libs lib32z1-dev lib32ncurses5-dev gcc-multilib g++-multilib

script:
  - bash travis.sh

cache:
  - ccache