os: linux
dist: trusty
sudo: required
language: cpp
compiler: gcc

before_install:
  - sudo apt-get update

install:
  - sudo apt-get -qq install g++-7 
  - sudo apt-get install -y axel xz-utils bc bison build-essential ccache curl flex g++-multilib gcc-multilib git gnupg gperf imagemagick lib32ncurses5-dev lib32readline-dev lib32z1-dev liblz4-tool libncurses5-dev libsdl1.2-dev libssl-dev libwxgtk3.0-dev libxml2 libxml2-utils lzop pngcrush rsync schedtool squashfs-tools xsltproc zip zlib1g-dev openjdk-8-jdk figlet

script:
  - bash travis.sh

cache:
  - ccache